// Code generated by "stringer -type=Region"; DO NOT EDIT.

package ines

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NTSC-0]
	_ = x[PAL-1]
	_ = x[Multiple-2]
	_ = x[Dendy-3]
}

const _Region_name = "NTSCPALMultipleDendy"

var _Region_index = [...]uint8{0, 4, 7, 15, 20}

func (i Region) String() string {
	if i >= Region(len(_Region_index)-1) {
		return "Region(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Region_name[_Region_index[i]:_Region_index[i+1]]
}
