version: 2
project_name: nestor

before:
  hooks:
    - go mod tidy

builds:
  - id: nestor
    binary: nestor
    env:
      - CGO_ENABLED=1
    goos:
      - GOOS_PLACEHOLDER
    goarch:
      - GOARCH_PLACEHOLDER
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: nestor
    homepage: "https://github.com/arl/nestor"
    description: "Nestor is a NES/Famicom emulator written in Go."
    license: "MIT"
    url_template: "https://github.com/arl/nestor/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    skip_upload: false
    repository:
      owner: arl
      name: homebrew-arl
      branch: main
    commit_author:
      name: goreleaser-bot
      email: bot@goreleaser.com
    test: |
      system "#{bin}/nestor -version"
