on: [push, pull_request]
name: Test, Build and Publish
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: tests
          key: tests-dir

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install
          gcc
          libegl1-mesa-dev
          libffi-dev
          libgles2-mesa-dev
          libvulkan-dev
          libwayland-dev
          libx11-dev
          libx11-xcb-dev
          libxcursor-dev
          libxkbcommon-x11-dev
          pkg-config

      - name: Run tests
        run: go test -race -shuffle=on ./...
