on: [push, pull_request]
name: Test, Build and Publish
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Run tests
        run: go test -race -shuffle=on ./...

