on: [push, pull_request]
name: test and build on linux
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: tests
          key: tests-dir

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          stable: false

      - name: go generate check
        run: |
          go generate ./...
          git diff --name-only --exit-code

      - name: Dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install
          gcc
          libasound2-dev
          libc6-dev
          libgl1-mesa-dev
          libxcursor-dev
          libxi-dev
          libxinerama-dev
          libxrandr-dev
          libxxf86vm-dev
          pkg-config

      # Run tests, with export DISPLAY=:0
      - name: Run tests
        env:
          DISPLAY: ":0"
        run: go test -shuffle=on ./...
