on: [push, pull_request]
name: test and build on linux
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: tests
          key: tests-dir

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          stable: false

      - name: go generate check
        run: >-
          go generate ./...
          git diff --name-only --exit-code

      - name: Dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install
          gcc
          pkg-config
          libsdl2-dev
          libgtk-3-dev
          libglib2.0-dev
          libgdk-pixbuf-2.0-dev
          libsdl2-image-dev
          libsdl2-mixer-dev
          libsdl2-ttf-dev
          libsdl2-gfx-dev

      - name: Run tests
        run: go test -shuffle=on ./...
