name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux/amd64
            goos: linux
            goarch: amd64
          - os: macos-13
            name: macOS/amd64
            goos: darwin
            goarch: amd64
          - os: macos-latest
            name: macOS/arm64
            goos: darwin
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libgtk-3-dev

      - name: Build Binary
        env:
          CGO_ENABLED: 1
        run: |
          VERSION="${{ github.ref_name }}"
          
          go build -trimpath -ldflags="-s -w" -o nestor .
          
          # Create archive
          tar czf nestor_${VERSION}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz nestor LICENSE.md README.md
          
          # Generate checksum
          if [ "$RUNNER_OS" == "Linux" ]; then
            sha256sum nestor_${VERSION}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz > nestor_${VERSION}_checksums_${{ matrix.goos }}_${{ matrix.goarch }}.txt
          else
            shasum -a 256 nestor_${VERSION}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz > nestor_${VERSION}_checksums_${{ matrix.goos }}_${{ matrix.goarch }}.txt
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nestor_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
            nestor_${{ github.ref_name }}_checksums_${{ matrix.goos }}_${{ matrix.goarch }}.txt
          generate_release_notes: true
          fail_on_unmatched_files: true
